/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as botVaultFlattenedSol from './BotVault_Flattened.sol/index.js';
export { BotVault__factory } from './BotVault__factory.js';