/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace BotVault {
      
    export type VaultStruct = {vaultId: BigNumberish, owner: AddressLike, amount: BigNumberish, unlockTime: BigNumberish, createdAt: BigNumberish, withdrawn: boolean}

    export type VaultStructOutput = [vaultId: bigint, owner: string, amount: bigint, unlockTime: bigint, createdAt: bigint, withdrawn: boolean] & {vaultId: bigint, owner: string, amount: bigint, unlockTime: bigint, createdAt: bigint, withdrawn: boolean }
  
    }

  export interface BotVaultInterface extends Interface {
    getFunction(nameOrSignature: "createVault" | "deposit" | "getUserVaults" | "getVault" | "getVaultCount" | "isUnlocked" | "status" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "VaultCreated" | "VaultDeposit" | "VaultWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'createVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserVaults', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getVaultCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isUnlocked', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'status', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserVaults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVaultCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUnlocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'status', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace VaultCreatedEvent {
      export type InputTuple = [vaultId: BigNumberish, owner: AddressLike, amount: BigNumberish, unlockTime: BigNumberish];
      export type OutputTuple = [vaultId: bigint, owner: string, amount: bigint, unlockTime: bigint];
      export interface OutputObject {vaultId: bigint, owner: string, amount: bigint, unlockTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultDepositEvent {
      export type InputTuple = [vaultId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [vaultId: bigint, amount: bigint];
      export interface OutputObject {vaultId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultWithdrawnEvent {
      export type InputTuple = [vaultId: BigNumberish, owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [vaultId: bigint, owner: string, amount: bigint];
      export interface OutputObject {vaultId: bigint, owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BotVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): BotVault;
    waitForDeployment(): Promise<this>;

    interface: BotVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createVault: TypedContractMethod<
      [unlockTime: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    deposit: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getUserVaults: TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getVault: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [BotVault.VaultStructOutput],
      'view'
    >
    

    
    getVaultCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isUnlocked: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    status: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createVault'): TypedContractMethod<
      [unlockTime: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getUserVaults'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVault'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [BotVault.VaultStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getVaultCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isUnlocked'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'status'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [vaultId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'VaultCreated'): TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
getEvent(key: 'VaultDeposit'): TypedContractEvent<VaultDepositEvent.InputTuple, VaultDepositEvent.OutputTuple, VaultDepositEvent.OutputObject>;
getEvent(key: 'VaultWithdrawn'): TypedContractEvent<VaultWithdrawnEvent.InputTuple, VaultWithdrawnEvent.OutputTuple, VaultWithdrawnEvent.OutputObject>;

    filters: {
      
      'VaultCreated(uint256,address,uint256,uint256)': TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
      VaultCreated: TypedContractEvent<VaultCreatedEvent.InputTuple, VaultCreatedEvent.OutputTuple, VaultCreatedEvent.OutputObject>;
    

      'VaultDeposit(uint256,uint256)': TypedContractEvent<VaultDepositEvent.InputTuple, VaultDepositEvent.OutputTuple, VaultDepositEvent.OutputObject>;
      VaultDeposit: TypedContractEvent<VaultDepositEvent.InputTuple, VaultDepositEvent.OutputTuple, VaultDepositEvent.OutputObject>;
    

      'VaultWithdrawn(uint256,address,uint256)': TypedContractEvent<VaultWithdrawnEvent.InputTuple, VaultWithdrawnEvent.OutputTuple, VaultWithdrawnEvent.OutputObject>;
      VaultWithdrawn: TypedContractEvent<VaultWithdrawnEvent.InputTuple, VaultWithdrawnEvent.OutputTuple, VaultWithdrawnEvent.OutputObject>;
    
    };
  }